/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;

import java.util.Random;
import java.util.Scanner;

import ifsc.poo.classes.Lampada;
import ifsc.poo.classes.Pessoa;
import ifsc.poo.classes.Produto;
import ifsc.poo.classes.Relogio;
import ifsc.poo.classes.Retangulo;

public class App {

    public static void main(String[] args) {

        try (Scanner scanner = new Scanner(System.in)) {
            System.out.println("Selecione qual teste você gostaria de fazer (Escolher de 1-5):");
            System.out.println("1 - Teste da Lâmpada");
            System.out.println("2 - Teste da Pessoa");
            System.out.println("3 - Teste do Retângulo");
            System.out.println("4 - Teste do Relógio");
            System.out.println("5 - Teste do Produto");
            System.out.print("> ");
            int escolha = scanner.nextInt();
            
            switch(escolha){
                case 1 -> TesteLampada();
                
                case 2 -> TestePessoa();
                
                case 3 -> TesteRetangulo();
                
                case 4 -> TesteRelogio();
                
                case 5 -> TesteProduto();
                
                default -> System.out.println("Argumento inválido");
            }
        }
    }

    public static void TesteLampada(){
        Lampada lampada1 = new Lampada();
        Lampada lampada2 = new Lampada();

        lampada1.ligar();
        lampada2.desligar();

        System.out.println("Lampada 1 está ligada?: " + lampada1.Estado());
        System.out.println("Lampada 2 está ligada?: " + lampada2.Estado());
        
    }

    public static void TestePessoa(){
        Pessoa pessoa1 = new Pessoa();
        Pessoa pessoa2 = new Pessoa();
        
        pessoa1.setNome("Alice");
        pessoa1.setIdade(22);

        pessoa2.setNome("Bruno");
        pessoa2.setIdade(25);

        pessoa2.felizAniversario();
        pessoa2.felizAniversario();
        pessoa2.felizAniversario();

        System.out.printf("A idade de %s é %d\n", pessoa1.getNome(), pessoa1.getIdade());
        System.out.printf("A idade de %s é %d\n", pessoa2.getNome(), pessoa2.getIdade());

        // pessoa1.setIdade(-44);
        // pessoa2.setNome("");

        /*
            Os dois últimos atributos estão comentados por não compilar o código, já que retorna erros já previstos na classe
        */
    }

    public static void TesteRetangulo(){
        Retangulo retangulo = new Retangulo();
        retangulo.setLargura(5);
        retangulo.setAltura(4);

        System.out.printf("A área do retângulo é 20: %b\nSeu perímetro é 18: %b\n", (retangulo.getArea() == 20), (retangulo.getPerimetro() == 18));
    
        Retangulo retangulos[] = new Retangulo[10];
        Random rand = new Random();

        for (int i = 0; i < 10; i++) {
            retangulos[i] = new Retangulo();
            retangulos[i].setLargura(rand.nextInt(10) + 1);
            retangulos[i].setAltura(rand.nextInt(10) + 1);
        }

        float maiorRazao = 0;
        Retangulo melhorRetangulo = null;
    
        for (Retangulo r : retangulos) {
            float razao = r.getArea() / r.getPerimetro();
            if (razao > maiorRazao) {
                maiorRazao = razao;
                melhorRetangulo = r;
            }
        }
    
        if (melhorRetangulo != null) {
            System.out.printf("O retângulo com a maior razão área/perímetro tem largura %.2f, altura %.2f, razão %.2f\n",
                melhorRetangulo.getLargura(), melhorRetangulo.getAltura(), maiorRazao);
        }
    
    }

    public static void TesteRelogio(){
        Relogio relogio = new Relogio();
        relogio.ajustaHora((byte)14, (byte)58, (byte)32);

        relogio.avancaMinuto();
        relogio.avancaMinuto();

        System.out.println(relogio.getHora());

        relogio.ajustaHora((byte)23, (byte)59, (byte)59);
        relogio.avancaSegundo();

        System.out.println(relogio.getHora());
    }

    public static void TesteProduto(){
        Produto produto_um = new Produto("Geladeira", 832);
        Produto produto_dois = new Produto("Micro-ondas", 499);

        produto_um.setDesconto(6);
        produto_dois.setDesconto(12);

        aplicarDesconto(produto_um);
        aplicarDesconto(produto_dois);

        System.out.printf("Produto: %s, novo preço: %.2f\n", produto_um.getNome(), produto_um.getPreco());
        System.out.printf("Produto: %s, novo preço: %.2f\n", produto_dois.getNome(), produto_dois.getPreco());

        System.out.println(produto_um.anuncio());
    }

    private static void aplicarDesconto(Produto produto) {
        float precoComDesconto = produto.getPreco() - (produto.getPreco() * produto.getDesconto() / 100);
        produto.setPreco((int) precoComDesconto);
    }
}
